### ISSUE TITLE
doesn not work in Edge 15

### ISSUE THREAD

**Issue by Mafti** [deanhume/lazy-observer-load#2]
Hi,

Currently it does not work in edge15:
Object doesn't support property or method 'forEach'

**Comment by deanhume** [comment]
Hi @Mafti  - good spot, Ill take a look at this...

**Comment by deanhume** [comment]
Hi @Mafti - the latest version of the [minified file](https://github.com/deanhume/lazy-observer-load/blob/master/lazy-load.min.js) should now work in IE Edge.

Thanks for reporting this 👍

**Comment by CyrilKrylatov** [comment]
Hello @deanhume it seems like it's kind of broken again on Edge 44.17 / EdgeHTML 18.17.

I'm importing the minified file (I'm using Webpack)
```js
import LazyLoad from 'lazy-observer-load/lazy-load.min.js'
document.addEventListener('DOMContentLoaded', function() {
    launchLazyLoad();
});
function launchLazyLoad() {
    const launchLazyLoad = LazyLoad.init();
}
```

If I JSFormat the minified file and then drop some console.log like this:
```js
var LazyLoad = {
    init: function init(a) {
        console.log("init");
        if (config = _extends({}, defaults, a), images = document.querySelectorAll(config.imageSelector), imageCount = images.length, !('IntersectionObserver' in window)) loadImagesImmediately(images);
        console.log("images", images);
``` 
I only have the first one that pop on Edge's console, not the second.

I don't have any other errors in there.

Do you have any clue?

Thank you!
