### ISSUE TITLE
Plans for npm support?

### ISSUE THREAD

**Issue by rejas** [deanhume/lazy-observer-load#4]
Title says it all, do you plan on publishing it on the npm registry? Thx in advance

**Comment by deanhume** [comment]
Hi @rejas 

I'd love to - I just need to get round to it!

**Comment by rejas** [comment]
Hi Dean, wanted to get back to this topic, need some help with it? Or will you not maintain the lib anymore?

**Comment by rejas** [comment]
pinging @deanhume :-)

**Comment by deanhume** [comment]
hey @rejas - happy for you to add it to NPM if you want!

**Comment by rejas** [comment]
Well, I modified your code in my repo already a little more so even if you'd add it to NPM I couldnt use it. But maybe you like the changes I made in https://github.com/rejas/veeck.de/blob/master/src/js/modules/lazy.js ?
In short: Made it a little more configurable and exportable ;-) Any thoughts on those changes?

**Comment by deanhume** [comment]
I like it....the only thing is I see a reference to [core-js](https://github.com/rejas/veeck.de/blob/8de4be2a4faa806aac8ebdb6aa26e631771e8aae/src/js/modules/lazy.js#L2), which means that in order to use lazy load, developers will need to download an additional library and thus adding to their page weight.

Is there any way we can do it without this additional library?

**Comment by rejas** [comment]
That library is only needed for IE11 support (see https://caniuse.com/#feat=promises). So I think it can be removed and maybe a hint added to the README on how to enable it for IE11 users.

**Comment by rejas** [comment]
Thx for merging my little PR. So, now what about publishing this gem to NPM @deanhume ? ;-)

**Comment by deanhume** [comment]
Sounds like a plan. 

I was wondering if you could take a look at the index.html page and the lazy.min.js file? - I've taken your updated and minified  the code, but its now broken the test page 😞

**Comment by rejas** [comment]
Will do once I am back in the office later :-)

**Comment by rejas** [comment]
Fixed via https://github.com/deanhume/lazy-observer-load/pull/15/files

**Comment by deanhume** [comment]
If you want to add this to NPM yourself - I am happy for you to go for it?

I won't have time maintain it myself unfortunately!

**Comment by rejas** [comment]
Alrighty then, I published it myself, see https://www.npmjs.com/package/lazy-observer-load :-) Maybe you can add a link to the npm page? Anyway, lots of thanks for your initial work, closing this issue now :-)
