### ISSUE TITLE
doesn not work in IE 11

### ISSUE THREAD

**Issue by qiweime** [deanhume/lazy-observer-load#6]
Hi,

The code is blocked，Unable to load picture in Internet explorer . Please help to check it~

**Comment by ep90** [comment]
I'm also seeing this problem,  IE 11 does not support promises so is failing here:

 `return new Promise((resolve, reject) => {`

and doesn't like "from" so it also failing with error:  Object doesn't support property or method 'from'

To repeat:

In IE 11, open the working example page:
 https://deanhume.github.io/lazy-observer-load/  

right click, inspect element, click on the console tab

The error is shown

**Comment by rejas** [comment]
Hi guys and girls, you can get IE11 to work if you import the core.js library in your project like I did in my project there: https://github.com/rejas/veeck.de/blob/8de4be2a4faa806aac8ebdb6aa26e631771e8aae/src/js/modules/lazy.js#L2
