### ISSUE TITLE
Improvement: Use disconnect function and return after it

### ISSUE THREAD

**Issue by beachespecially** [deanhume/lazy-observer-load#8]
Since I'm unable to create a PR:
- In lazy-load.js line 86 you could use the previously defined disconnect() function instead of observer.disconnect.
- Would it make sense to add a "return" after line 86? In my opinion the rest of the function doesn't have to be executed if imageCount === 0

**Comment by deanhume** [comment]
This has been merged and updated in #11 - thanks @rejas!
